apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loki
  labels:
    app.kubernetes.io/name: loki-redis
  name: loki-redis
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    tcp-keepalive 300
    loglevel notice
    databases 2
    save 900 1  
    save 300 10
    save 60 10000
    dir /var/lib/redis
    appendonly no
    maxmemory 8589934592