apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-redis-metrics
  namespace: loki
  labels:
    app.kubernetes.io/name: loki-redis
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-redis
  endpoints:
    - port: metrics
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host