apiVersion: v1
kind: ConfigMap
metadata:
  namespace:  loki
  labels:
    app.kubernetes.io/name: loki-system
  name: loki-local-config
data:
  local-config.yaml: |-
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      http_listen_address: 0.0.0.0
      grpc_listen_port: 9095
      grpc_listen_address: 0.0.0.0
      grpc_server_max_recv_msg_size: 10000000
      grpc_server_max_send_msg_size: 10000000
      grpc_server_max_concurrent_streams: 0

    memberlist:
      join_members: ["loki-system-0.loki-system-headless.loki.svc.cluster.local", "loki-system-1.loki-system-headless.loki.svc.cluster.local", "loki-system-2.loki-system-headless.loki.svc.cluster.local"]
      dead_node_reclaim_time: 30s
      gossip_to_dead_nodes_time: 15s
      left_ingesters_timeout: 30s
      bind_addr: ['0.0.0.0']
      bind_port: 7946

    querier:
      query_ingesters_within: 2h
    
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      downstream_url: http://loki-system:3100

    query_range:
      split_queries_by_interval: 24h
      align_queries_with_step: true
      max_retries: 5
      results_cache:
        cache:
          redis:
            endpoint: loki-redis-0.loki-redis.loki.svc.cluster.local:6379
            expiration: 1h
      cache_results: true
    
    ingester:
      lifecycler:
        join_after: 60s
        observe_period: 5s
        ring:
          replication_factor: 2
          kvstore:
            store: memberlist
        final_sleep: 0s
      chunk_idle_period: 1h
      max_chunk_age: 1h
      chunk_retain_period: 1m
      max_transfer_retries: 1
      chunk_encoding: snappy
      chunk_target_size: 0
      chunk_block_size: 262144

    ingester_client:
      grpc_client_config:
          max_recv_msg_size: 20971520
      remote_timeout: 1s
    
    schema_config:
      configs:
      - from: 2021-04-25
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: index_
          period: 24h
    
    storage_config:
      boltdb_shipper:
        shared_store: aws
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
    
      aws:
        s3: s3://__S3_ACCESS_KEY__:__S3_SECRET_KEY__@__S3_HOST__/logchunks
        s3forcepathstyle: true
        insecure: true
    
      index_queries_cache_config:
        redis:
          endpoint: loki-redis-0.loki-redis.loki.svc.cluster.local:6379
          expiration: 1h
    
    chunk_store_config:
      chunk_cache_config:
        redis:
          endpoint: loki-redis-0.loki-redis.loki.svc.cluster.local:6379
          expiration: 1h
      max_look_back_period: 0    
      write_dedupe_cache_config:
       redis:
          endpoint: loki-redis-0.loki-redis.loki.svc.cluster.local:6379
          expiration: 1h
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 64
      ingestion_burst_size_mb: 128
      max_entries_limit_per_query: 50000
    
    ruler:
      storage:
        type: s3
        s3:
          s3: s3://__S3_ACCESS_KEY__:__S3_SECRET_KEY__@__S3_HOST__/logrules
          s3forcepathstyle: true
          insecure: true
          http_config:
            insecure_skip_verify: true
      enable_api: true
      enable_alertmanager_v2: true
      alertmanager_url: "http://"
      ring:
        kvstore:
          store: inmemory
    
    table_manager:
        chunk_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        index_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        retention_deletes_enabled: false
        retention_period: 0