apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: loki
  labels:
    app.kubernetes.io/name: loki-gateway
spec:
  type: NodePort
  ports:
    - name: http-3100
      port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app.kubernetes.io/name: loki-gateway