replicaCount: 1

image:
  repository: bitnami/cassandra:3-debian-10
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
svcNameOverride: ""

service:
  type: ClusterIP
  ports:
  - name: http-7000
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: http-9042
    port: 9042
    protocol: TCP
    targetPort: 9042

resources: 
  requests:
    cpu: 500m
    memory: 8Gi
  limits:
    cpu: "1"
    memory: 10Gi

livenessProbe:
  failureThreshold: 130
  initialDelaySeconds: 300
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
  tcpSocket:
    port: 9042
  
nodeSelector: {}
tolerations: []
affinity: {}

volumeMounts: []

volumes: []